#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/glm5_next/modular_glm5_next.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_glm5_next.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 the HuggingFace Team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from huggingface_hub.dataclasses import strict

from ...configuration_utils import PreTrainedConfig
from ...modeling_rope_utils import RopeParameters
from ...utils import auto_docstring


@auto_docstring(checkpoint="zai-org/GLM-5-Next")
@strict
class Glm5NextConfig(PreTrainedConfig):
    r"""
    mla_nope (`bool`, *optional*, defaults to `True`):
        Whether MLA full-attention layers use the no-RoPE key path shipped by
        the current checkpoint layout.
    n_group (`int`, *optional*, defaults to 1):
        Number of routed expert groups.
    first_k_dense_replace (`int`, *optional*, defaults to 3):
        Number of initial dense MLP layers before sparse MoE layers.
    scoring_func (`str`, *optional*, defaults to `"sigmoid"`):
        Router score activation name kept for checkpoint/config compatibility.
    topk_method (`str`, *optional*, defaults to `"noaux_tc"`):
        Routed expert top-k selection method name.
    swiglu_limit (`float`, *optional*, defaults to 10.0):
        Clamp limit applied to SwiGLU gate/up projections.
    linear_attn_config (`dict`, *optional*):
        KDA linear attention layout and dimensions. Layers listed in
        `kda_layers` use KDA; layers listed in `full_attn_layers` use MLA.
    linear_conv_kernel_dim (`int`, *optional*, defaults to 4):
        Short convolution kernel size used by KDA query/key/value projections.
    linear_key_head_dim (`int`, *optional*, defaults to 128):
        Per-head key/query dimension used when building the default KDA config.
    linear_value_head_dim (`int`, *optional*, defaults to 128):
        Per-head value dimension kept for compatibility with upstream GLM-5-Next configs.
    linear_num_key_heads (`int`, *optional*, defaults to 64):
        Number of KDA key/query heads used when building the default KDA config.
    linear_num_value_heads (`int`, *optional*, defaults to 64):
        Number of KDA value heads kept for compatibility with upstream GLM-5-Next configs.
    linear_allow_neg_eigval (`bool`, *optional*, defaults to `False`):
        Compatibility flag for KDA kernels that support negative eigenvalues.
    mhc (`bool`, *optional*, defaults to `True`):
        Whether to use Manifold-Constrained Hyper-Connection residual streams.
    hc_mult (`int`, *optional*, defaults to 4):
        Number of MHC residual streams. Set `mhc=False` or `hc_mult=0` to
        use the standard residual path in tiny tests or ablations.
    hc_eps (`float`, *optional*, defaults to 1e-6):
        Numerical floor used by MHC Sinkhorn normalization.
    hc_sinkhorn_iters (`int`, *optional*, defaults to 20):
        Number of Sinkhorn iterations used by MHC routing.
    mhc_post_mult_value (`float`, *optional*, defaults to 2.0):
        Post multiplier applied by MHC after each sublayer.
    mhc_no_norm_weight (`bool`, *optional*, defaults to `True`):
        Compatibility flag for MHC checkpoints without norm weights.
    index_head_dim (`int`, *optional*, defaults to 128):
        DSA indexer projection head dimension.
    index_n_heads (`int`, *optional*, defaults to 32):
        Number of DSA indexer heads.
    index_topk (`int`, *optional*, defaults to 2048):
        Number of sparse-attention positions selected by the DSA indexer.
    indexer_rope_interleave (`bool`, *optional*, defaults to `True`):
        Whether the DSA indexer uses interleaved RoPE.
    enable_dsa_indexer (`bool`, *optional*, defaults to `False`):
        Enables the optional DSA indexer scaffold when checkpoints contain
        `self_attn.indexer.*` weights.
    indexer_types (`list[str]`, *optional*):
        Per-layer DSA indexer mode. Values are `"full"` or `"shared"`.
    rope_interleave (`bool`, *optional*, defaults to `True`):
        Whether the main attention RoPE uses interleaved layout.
    mlp_layer_types (`list[str]`, *optional*):
        Per-layer feed-forward schedule. Values are `"dense"` or `"sparse"`.
    """

    model_type = "glm5_next"
    keys_to_ignore_at_inference = ["past_key_values"]

    attribute_map = {
        "num_local_experts": "n_routed_experts",
        "head_dim": "qk_nope_head_dim",
    }

    base_model_tp_plan = {
        "layers.*.self_attn.q_b_proj": "colwise",
        "layers.*.self_attn.kv_a_proj_with_mqa": "mla_kv_a_proj",
        "layers.*.self_attn.kv_b_proj": "colwise",
        "layers.*.self_attn.o_proj": "rowwise",
        "layers.*.mlp.experts": "moe_tp_experts",
        "layers.*.mlp.experts.*.gate_proj": "colwise",
        "layers.*.mlp.experts.*.up_proj": "colwise",
        "layers.*.mlp.experts.*.down_proj": "rowwise",
        "layers.*.mlp.shared_experts.gate_proj": "colwise",
        "layers.*.mlp.shared_experts.up_proj": "colwise",
        "layers.*.mlp.shared_experts.down_proj": "rowwise",
        "layers.*.mlp.gate_proj": "colwise",
        "layers.*.mlp.up_proj": "colwise",
        "layers.*.mlp.down_proj": "rowwise",
    }
    base_model_pp_plan = {
        "embed_tokens": (["input_ids"], ["inputs_embeds"]),
        "layers": (["hidden_states", "attention_mask"], ["hidden_states"]),
        "norm": (["hidden_states"], ["hidden_states"]),
    }

    vocab_size: int = 154880
    hidden_size: int = 4096
    intermediate_size: int = 12288
    num_hidden_layers: int = 45
    num_attention_heads: int = 64
    num_key_value_heads: int = 64
    hidden_act: str = "silu"
    max_position_embeddings: int = 1104096
    initializer_range: float = 0.02
    rms_norm_eps: float = 1e-5
    use_cache: bool = True
    tie_word_embeddings: bool = False
    rope_parameters: RopeParameters | dict | None = None
    attention_bias: bool = False
    attention_dropout: float | int = 0.0

    head_dim: int = 192
    q_lora_rank: int | None = 1536
    kv_lora_rank: int = 512
    qk_nope_head_dim: int = 192
    qk_rope_head_dim: int = 64
    v_head_dim: int = 256
    mla_nope: bool = True

    moe_intermediate_size: int = 2048
    num_experts_per_tok: int = 7
    n_shared_experts: int = 1
    n_routed_experts: int = 288
    routed_scaling_factor: float = 2.5
    n_group: int = 1
    topk_group: int = 1
    first_k_dense_replace: int = 3
    norm_topk_prob: bool = True
    scoring_func: str = "sigmoid"
    topk_method: str = "noaux_tc"
    swiglu_limit: float = 10.0

    linear_attn_config: dict | None = None
    linear_conv_kernel_dim: int = 4
    linear_key_head_dim: int = 128
    linear_value_head_dim: int = 128
    linear_num_key_heads: int = 64
    linear_num_value_heads: int = 64
    linear_allow_neg_eigval: bool = False

    use_qk_norm: bool = True
    mhc: bool = True
    hc_mult: int = 4
    hc_eps: float = 1e-6
    hc_sinkhorn_iters: int = 20
    mhc_post_mult_value: float = 2.0
    mhc_no_norm_weight: bool = True

    index_head_dim: int = 128
    index_n_heads: int = 32
    index_topk: int = 2048
    indexer_rope_interleave: bool = True
    enable_dsa_indexer: bool = False
    indexer_types: list[str] | None = None

    rope_interleave: bool = True
    bos_token_id: int | None = None
    eos_token_id: int | list[int] | None = None
    pad_token_id: int | None = 154820
    mlp_layer_types: list[str] | None = None

    def __post_init__(self, **kwargs):
        if self.num_key_value_heads is None:
            self.num_key_value_heads = self.num_attention_heads

        if self.rope_parameters is None:
            self.rope_parameters = {
                "rope_type": "default",
                "rope_theta": 10000.0,
                "partial_rotary_factor": 1.0,
            }

        if self.linear_attn_config is None:
            kda_layers = [idx for idx in range(self.num_hidden_layers) if idx % 4 != 3]
            full_attn_layers = [idx for idx in range(self.num_hidden_layers) if idx % 4 == 3]
            self.linear_attn_config = {
                "full_attn_layers": full_attn_layers,
                "head_dim": self.linear_key_head_dim,
                "kda_layers": kda_layers,
                "num_heads": self.linear_num_key_heads,
                "short_conv_kernel_size": self.linear_conv_kernel_dim,
            }

        self.qk_head_dim = self.qk_nope_head_dim + self.qk_rope_head_dim

        if self.mlp_layer_types is None:
            self.mlp_layer_types = [
                "dense" if layer_idx < self.first_k_dense_replace else "sparse"
                for layer_idx in range(self.num_hidden_layers)
            ]

        if self.indexer_types is None:
            pattern = kwargs.pop("index_topk_pattern", None)
            freq = kwargs.pop("index_topk_freq", 1)
            if isinstance(pattern, str):
                self.indexer_types = [{"F": "full", "S": "shared"}[char] for char in pattern]
            elif pattern is not None:
                self.indexer_types = list(pattern)
            else:
                self.indexer_types = [
                    "full" if (max(layer_idx - 1, 0) % freq) == 0 else "shared"
                    for layer_idx in range(self.num_hidden_layers)
                ]

        super().__post_init__(**kwargs)


__all__ = ["Glm5NextConfig"]
